server:
  port: 8078
spring:
  application:
    name: mongodb-pro
  data:
    mongodb:
      uri: mongodb://101.42.156.68:27017/baizhi
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver